/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:43:14 GMT 2020
 */

package array;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import array.ContainsDuplicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContainsDuplicate_ESTest extends ContainsDuplicate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContainsDuplicate containsDuplicate0 = new ContainsDuplicate();
      // Undeclared exception!
      try { 
        containsDuplicate0.containsDuplicate((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("array.ContainsDuplicate", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ContainsDuplicate containsDuplicate0 = new ContainsDuplicate();
      int[] intArray0 = new int[2];
      boolean boolean0 = containsDuplicate0.containsDuplicate(intArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ContainsDuplicate containsDuplicate0 = new ContainsDuplicate();
      int[] intArray0 = new int[0];
      boolean boolean0 = containsDuplicate0.containsDuplicate(intArray0);
      assertFalse(boolean0);
  }
}
