/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:41:05 GMT 2020
 */

package array;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import array.TwoSum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TwoSum_ESTest extends TwoSum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TwoSum twoSum0 = new TwoSum();
      int[] intArray0 = new int[4];
      intArray0[0] = 570;
      intArray0[1] = 533;
      int[] intArray1 = twoSum0.twoSum(intArray0, 570);
      assertArrayEquals(new int[] {0, 2, 3}, intArray1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TwoSum twoSum0 = new TwoSum();
      // Undeclared exception!
      try { 
        twoSum0.twoSum((int[]) null, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("array.TwoSum", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TwoSum twoSum0 = new TwoSum();
      int[] intArray0 = new int[2];
      int[] intArray1 = twoSum0.twoSum(intArray0, 531);
      assertEquals(0, intArray1.length);
  }
}
